/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class CalcTest {
    @Test
    public void addTest() {
        Calc classUnderTest = new Calc();
        assertEquals(600, classUnderTest.add(100, 200, 300));
    }

    @Test
    public void subTest() {
        Calc classUnderTest = new Calc();
        assertEquals(100, classUnderTest.sub(100, 200));
    }

}
