/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.0.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // This states that this is a java-lib
    `java-library`
    // This helps to publish to maven repo
    `maven-publish`
    // for spring boot
    libs.plugins.spring.boot
}

publishing {
    publications {
        create<MavenPublication>("mavenJava") {
            // These lines override the defaults
            groupId = "com.suriyaprakhash"
            artifactId = "calc-lib"
            version = "0.0.2-SNAPSHOT"

            from(components["java"])
        }
    }
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    mavenLocal()
}

tasks.register("suriya") {
    group = "my-group"
    description = "this is for running suriya's tasks"
    print("hello world")
}

tasks.named("build") {
    finalizedBy("suriya")
}

dependencies {
    // This uses the BOM you defined
    api(platform(libs.spring.boot.bom))

    // Making this compile only since it going to be lib
    api(libs.spring.boot.starter.web)

    implementation(libs.guava)
    testImplementation(libs.junit.jupiter)
//    testImplementation(libs.spring.boot.starter.test)
    testRuntimeOnly(libs.junit.platform.launcher)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

