/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.springframework.stereotype.Service;

@Service
public class Calc {
    public int add(int... nosToAdd) {
        int sum = 0;
        for (int j : nosToAdd) {
            sum += j;
        }
        return sum;
    }

    public int sub(int... nosToSub) {
        int sub = 0;
        for (int j : nosToSub) {
            sub =  j - sub;
        }
        return sub;
    }
}
