/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Calc calc = new Calc();
        System.out.println(new App().getGreeting());
        System.out.println(calc.add(10,20,30));
    }
}
